name: TT语音打卡

on:
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: '0 1,10 * * *'
    # cron表达式，时区是UTC时间，比我们早8小时，如上所表示的是每天9点和18点
    # 建议每个人通过设置 GitHub Environments 的方式来设定为自己的目标运行时间（详细设置方法见文档说明）
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      # 检出
      - name: Checkout
        uses: actions/checkout@v2
      # 安装 Python
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: '安装 requirements'
        run: pip install -r ./requirements.txt 
        
      - name: '运行TT语音打卡脚本'  
        run: python3 TT_sign.py & python3 iphonee.py & python3 xr.py
        env:
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
            TG_USER_ID: ${{ secrets.TG_USER_ID }}
            uid: ${{ secrets.uid }}
            token: ${{ secrets.token }}
            xr_uid: ${{ secrets.xr_uid }}
            xr_token: ${{ secrets.xr_token }}
            p_uid: ${{ secrets.p_uid }}
            p_token: ${{ secrets.p_token }}
            dingding: ${{ secrets.dingding }}
